### ISSUE TITLE
Add macros for _assert*

### ISSUE THREAD

**Issue by yurrriq** [lfex/ltest#36]
I'm using these in [xlfe](https://github.com/exercism/xlfe) right now, but it'd be nice to bake something into ltest.

```lfe
(defmacro is-equal* (x y)
  `(_assertEqual ,x ,y))

(defmacro is-error* (x y)
  `(_assertError ,x ,y))
```

#### ~~TODO~~
- [x] Update `is-{,not-}exception{,*}`
- [x] Update `is-{,not-}error{,*}`
- [x] Update `is-{,not-}exit{,*}`
- [x] Update `is-{,not-}throw{,*}`

Add convenient unary clauses that pass `_` as the first argument to the binary versions.

**Comment by oubiwann** [comment]
I think this is a good idea -- you ready for a PR?

**Comment by yurrriq** [comment]
I don't have anything prepared yet. Also, I'm not sold on the `gen-` naming scheme. Do you have a better idea?

**Comment by rvirding** [comment]
Do you really need them? They just rename other macros. How about calling then assert-equal and assert-error?

**Comment by yurrriq** [comment]
@rvirding, we have those, but I need the `_`-prefixed ones, for writing test generators. It's totally a cosmetic concern to add lispy aliases. `(_assertEqual this that)` looks bad to me. :smiling_imp:

**Comment by yurrriq** [comment]
Oh hey! What about `assert-equal*` to follow the `*` naming scheme for alternates.

**Comment by rvirding** [comment]
Can you be consistent with the names? You could do assert-gen-equal and assert-gen-error. Consistent and explicit but maybe a bit long. Or not. Or assert-equal-gen and assert-error-gen?

**Comment by rvirding** [comment]
If you used assert-equal* etc then all the generator macros would have to end in '*', our version of starting with a '_'.

**Comment by yurrriq** [comment]
Right. That's what I was thinking. We can do postfix `*` for EUnit's prefix `_`.

**Comment by yurrriq** [comment]
I'm gonna do a PR while it's fresh in my mind, but then I'm really gonna work on lmug. :smile:

**Comment by oubiwann** [comment]
Nice! (to both)

**Comment by yurrriq** [comment]
Ok, so this got messier than I thought. I actually found [a bug](https://github.com/quasiquoting/lodox/issues/57) in the current version of Lodox when trying to generate ltest documentation...

There's also apparently a breaking change in EUnit somewhere around R18. I've separated the concerns into branches and `develop` has them all merged. [The tests are green](https://travis-ci.org/yurrriq/ltest/builds/117332163) on [my `develop` branch](https://github.com/yurrriq/ltest/tree/develop), but I still have to write/update generator tests.

**Comment by oubiwann** [comment]
This is why I value the Great Path of the Shaven Yak so highly :-) The road may not be direct -- nor easy -- but is has the power to give us better software if followed well and truly ... !

cc @cemerick

![meta-yak](https://cloud.githubusercontent.com/assets/894251/13908100/4472763c-eeca-11e5-96f5-7b394240e5b4.png)

**Comment by oubiwann** [comment]
I said it in PR #37 and I'll say it here: well done, @yurrriq! Great changes!

**Comment by yurrriq** [comment]
:tada: Cheers!
